const vehicles = {
  f150: {name:'Ford F-150', icon:'🚙', speed:42, fuel:68, voltage:'13.9V', ignition:true, door:'Locked', status:'Moving', heading:'Northeast', lat:36.1627, lng:-86.7816, color:'green'},
  transit: {name:'Ford Transit', icon:'🚐', speed:0, fuel:84, voltage:'12.7V', ignition:false, door:'Locked', status:'Parked', heading:'—', lat:36.1662, lng:-86.7765, color:'green'},
  silverado: {name:'Chevy Silverado', icon:'🚗', speed:0, fuel:51, voltage:'12.5V', ignition:false, door:'Open', status:'Parked', heading:'—', lat:36.1592, lng:-86.7892, color:'amber'}
};
let selected='f150';
const $=s=>document.querySelector(s);
function renderDetail(){const v=vehicles[selected];$('#detail').innerHTML=`<div class="detail-head"><button class="back" id="closeDetail">‹</button><div class="vehicle-icon large">${v.icon}</div><div><div class="detail-title">${v.name}</div><div class="muted"><span class="${v.color==='amber'?'warning':'online'}">● ${v.status}</span> · Updated just now</div></div></div><div class="detail-map"><div class="detail-grid-lines"></div><div class="detail-pin">${v.icon}</div></div><div class="detail-stats"><div><span>Speed</span><strong>${v.speed} mph</strong></div><div><span>Fuel</span><strong>${v.fuel}%</strong></div><div><span>Ignition</span><strong>${v.ignition?'On':'Off'}</strong></div><div><span>Door</span><strong>${v.door}</strong></div><div><span>Battery</span><strong>${v.voltage}</strong></div><div><span>Heading</span><strong>${v.heading}</strong></div></div><div class="quick-actions"><button>📍 Locate</button><button>⛽ Fuel</button><button>◷ History</button><button>⚠ Alerts</button></div>`;$('#detail').classList.add('open');$('#closeDetail').onclick=()=>$('#detail').classList.remove('open')}
function bind(){document.querySelectorAll('.vehicle').forEach((el,i)=>{const id=['f150','transit','silverado'][i];el.onclick=()=>{selected=id;document.querySelectorAll('.vehicle').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');renderDetail()}});document.querySelectorAll('.nav-item').forEach(n=>n.onclick=()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));n.classList.add('active')})}
function simulate(){const v=vehicles.f150;if(v.ignition){v.speed=Math.max(25,Math.min(55,v.speed+(Math.random()-.5)*6));v.fuel=Math.max(0,v.fuel-.01);const pin=$('.pin1');if(pin){pin.style.left=`${38+Math.sin(Date.now()/5000)*4}%`;pin.style.top=`${36+Math.cos(Date.now()/5000)*3}%`}}if(selected==='f150'&&$('#detail').classList.contains('open'))renderDetail();$('#liveSpeed').textContent=Math.round(v.speed);$('#liveFuel').textContent=Math.round(v.fuel)+'%'}
bind();setInterval(simulate,1500);